[build]
  command = "CI=true npm install && npx expo install --fix && npx expo export:web"
  publish = "web-build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 